TITLE: Ry4an's Unblog
TITLE_HTML: Ry4an's Unblog
TAGLINE: A blog about software, projects, and other little things I build.
#POSTS_PER_PAGE: 10
AUTHOR: Ry4an Brase
#DISQUS: your-disqus-id
TIMEZONE: UTC
FREEZER_BASE_URL: "//ry4an.org/unblog/"
