baseURL = 'https://ry4an.org/unblog/'
languageCode = 'en-us'
title = "Ry4an's Unblog"
theme = "terminal"

[security]
    [security.exec]
        allow = ["^rst2html", ]

[params]
    contentTypeName = "post"
